kind: Deployment
apiVersion: apps/v1
metadata:
   name: proj1
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: proj1
   template:
    metadata:
      labels:
          app: proj1
    spec:
      containers:
        - name: proj1
          image: chrisjonathan02/pipeline-demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"